// This file is auto-generated by scripts/generate-sidebar.js
// Do not edit this file directly.

export default [
  {
    "name": "首页",
    "path": "README"
  },
  {
    "name": "Guide",
    "children": [
      {
        "name": "Advanced",
        "path": "guide/advanced"
      },
      {
        "name": "Introduction",
        "path": "guide/introduction"
      }
    ]
  },
  {
    "name": "Api",
    "children": [
      {
        "name": "Api Overview",
        "path": "api/api-overview"
      },
      {
        "name": "Endpoints",
        "path": "api/endpoints"
      }
    ]
  }
];
