// ⚠️ AUTO-GENERATED by scripts/generate-manifest.mjs — do not edit by hand.
// Add markdown files under public/docs/ instead; this regenerates on dev/build.
// Generated: 2026-06-13T15:55:02.440Z

export const tree = [
  {
    "type": "page",
    "title": "贡献指南",
    "path": "贡献指南",
    "category": "",
    "icon": "✍️",
    "order": 0,
    "description": "三步即可新增或修改一篇 wiki 文档，零前端知识。",
    "tags": [
      "贡献",
      "帮助",
      "新手"
    ],
    "headings": [
      "三步新增一篇文档",
      "可选：用 Frontmatter 精细控制",
      "可选：为分类命名 / 排序",
      "图片怎么放",
      "背后发生了什么（了解即可）"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T14:58:48.073Z"
  },
  {
    "type": "category",
    "slug": "入学篇",
    "label": "入学篇",
    "icon": "✈️",
    "order": 1,
    "description": "行前准备、签证、机场指南、宿舍信息 —— 出发到马来西亚前后要知道的一切。",
    "children": [
      {
        "type": "page",
        "title": "吉隆坡机场指南",
        "path": "入学篇/吉隆坡机场指南",
        "category": "入学篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "行前指南",
        "path": "入学篇/行前指南",
        "category": "入学篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [
          "签证（个人签证与随行人员签证）",
          "英语（雅思/托福/PTE)",
          "必备物品"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "LY宿舍",
        "path": "入学篇/宿舍与室友",
        "category": "入学篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [
          "床"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      }
    ]
  },
  {
    "type": "category",
    "slug": "学习篇",
    "label": "学习篇",
    "icon": "🎓",
    "order": 2,
    "description": "选课、自学、工具推荐、小组作业与毕业设计，助你顺利攻克学业。",
    "children": [
      {
        "type": "page",
        "title": "毕业论文与毕业设计",
        "path": "学习篇/毕业论文与毕业设计",
        "category": "学习篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "全专业通用网站",
        "path": "学习篇/全专业通用网站",
        "category": "学习篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "善用工具",
        "path": "学习篇/善用工具",
        "category": "学习篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "小组作业生存指南",
        "path": "学习篇/小组作业生存指南",
        "category": "学习篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "自学",
        "path": "学习篇/自学",
        "category": "学习篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      }
    ]
  },
  {
    "type": "category",
    "slug": "生活篇",
    "label": "生活篇",
    "icon": "🏠",
    "order": 3,
    "description": "校园设施、周边环境、医疗、运动与好物分享，把日子过舒服。",
    "children": [
      {
        "type": "page",
        "title": "好物分享",
        "path": "生活篇/好物分享",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "马来西亚日常生活",
        "path": "生活篇/马来西亚日常生活",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "Grab(打车＋外卖）",
        "tags": [],
        "headings": [
          "外卖软件"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      },
      {
        "type": "page",
        "title": "如何与行政部门打交道",
        "path": "生活篇/如何与行政部门打交道",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "学校设施",
        "path": "生活篇/学校设施",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "学校周边",
        "path": "生活篇/学校周边",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "医疗",
        "path": "生活篇/医疗",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "智齿，智慧齿(wisdom teeth)常生长于18-19岁及以上的命苦大学生。智齿长出来时易挤压周边牙齿导致牙周炎和盲袋发炎，每个人智齿的生长情况各异，但拔掉智齿对大多数人来说是…",
        "tags": [],
        "headings": [
          "拔智齿"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T18:29:01+08:00"
      },
      {
        "type": "page",
        "title": "运动",
        "path": "生活篇/运动",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "生命在于运动。",
        "tags": [],
        "headings": [
          "校内运动场地",
          "各项运动氛围",
          "校运会Xenergy",
          "校外运动场地推荐"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      }
    ]
  },
  {
    "type": "category",
    "slug": "人生篇",
    "label": "人生篇",
    "icon": "🌏",
    "order": 4,
    "description": "关于厦马、国际视野与生涯规划 —— 站得更高，看得更远。",
    "children": [
      {
        "type": "page",
        "title": "高考招生咨询",
        "path": "人生篇/高考招生咨询",
        "category": "人生篇",
        "icon": "",
        "order": null,
        "description": "请关注厦大马校招办微信公众号获取与高考录取最新信息，本界面内容仅供参考",
        "tags": [],
        "headings": [
          "湖北省"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      },
      {
        "type": "page",
        "title": "关于厦马",
        "path": "人生篇/关于厦马",
        "category": "人生篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [
          "厦马总体介绍",
          "厦马的优势",
          "厦马的劣势",
          "- 985毕业证？留学跳板？你想在厦马有何收获?"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "国际视野",
        "path": "人生篇/国际视野",
        "category": "人生篇",
        "icon": "",
        "order": null,
        "description": "看到报考信息的你一定会了解到，这所学校与一带一路密不可分",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      }
    ]
  },
  {
    "type": "category",
    "slug": "api",
    "label": "开发文档",
    "icon": "🔌",
    "order": 9,
    "description": "面向开发者：站点 API 概览与接口列表。",
    "children": [
      {
        "type": "page",
        "title": "Api Overview",
        "path": "api/api-overview",
        "category": "api",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-03T12:44:22+08:00"
      },
      {
        "type": "page",
        "title": "Endpoints",
        "path": "api/endpoints",
        "category": "api",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-03T12:44:22+08:00"
      }
    ]
  }
];

export const pages = [
  {
    "type": "page",
    "title": "欢迎来到 XMUM Wiki",
    "path": "README",
    "category": "",
    "icon": "",
    "order": null,
    "description": "欢迎来到厦门大学马来西亚分校自救指南/XMUM Wiki！本项目旨在为厦大马校的同学们提供一个全面的信息共享平台，帮助大家更好地适应和享受在马校的学习与生活。",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-21T18:29:01+08:00"
  },
  {
    "type": "page",
    "title": "贡献指南",
    "path": "贡献指南",
    "category": "",
    "icon": "✍️",
    "order": 0,
    "description": "三步即可新增或修改一篇 wiki 文档，零前端知识。",
    "tags": [
      "贡献",
      "帮助",
      "新手"
    ],
    "headings": [
      "三步新增一篇文档",
      "可选：用 Frontmatter 精细控制",
      "可选：为分类命名 / 排序",
      "图片怎么放",
      "背后发生了什么（了解即可）"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T14:58:48.073Z"
  },
  {
    "type": "page",
    "title": "吉隆坡机场指南",
    "path": "入学篇/吉隆坡机场指南",
    "category": "入学篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "行前指南",
    "path": "入学篇/行前指南",
    "category": "入学篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [
      "签证（个人签证与随行人员签证）",
      "英语（雅思/托福/PTE)",
      "必备物品"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "LY宿舍",
    "path": "入学篇/宿舍与室友",
    "category": "入学篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [
      "床"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "毕业论文与毕业设计",
    "path": "学习篇/毕业论文与毕业设计",
    "category": "学习篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "全专业通用网站",
    "path": "学习篇/全专业通用网站",
    "category": "学习篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "善用工具",
    "path": "学习篇/善用工具",
    "category": "学习篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "小组作业生存指南",
    "path": "学习篇/小组作业生存指南",
    "category": "学习篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "自学",
    "path": "学习篇/自学",
    "category": "学习篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "好物分享",
    "path": "生活篇/好物分享",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "马来西亚日常生活",
    "path": "生活篇/马来西亚日常生活",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "Grab(打车＋外卖）",
    "tags": [],
    "headings": [
      "外卖软件"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "如何与行政部门打交道",
    "path": "生活篇/如何与行政部门打交道",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "学校设施",
    "path": "生活篇/学校设施",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "学校周边",
    "path": "生活篇/学校周边",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "医疗",
    "path": "生活篇/医疗",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "智齿，智慧齿(wisdom teeth)常生长于18-19岁及以上的命苦大学生。智齿长出来时易挤压周边牙齿导致牙周炎和盲袋发炎，每个人智齿的生长情况各异，但拔掉智齿对大多数人来说是…",
    "tags": [],
    "headings": [
      "拔智齿"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T18:29:01+08:00"
  },
  {
    "type": "page",
    "title": "运动",
    "path": "生活篇/运动",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "生命在于运动。",
    "tags": [],
    "headings": [
      "校内运动场地",
      "各项运动氛围",
      "校运会Xenergy",
      "校外运动场地推荐"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "高考招生咨询",
    "path": "人生篇/高考招生咨询",
    "category": "人生篇",
    "icon": "",
    "order": null,
    "description": "请关注厦大马校招办微信公众号获取与高考录取最新信息，本界面内容仅供参考",
    "tags": [],
    "headings": [
      "湖北省"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "关于厦马",
    "path": "人生篇/关于厦马",
    "category": "人生篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [
      "厦马总体介绍",
      "厦马的优势",
      "厦马的劣势",
      "- 985毕业证？留学跳板？你想在厦马有何收获?"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "国际视野",
    "path": "人生篇/国际视野",
    "category": "人生篇",
    "icon": "",
    "order": null,
    "description": "看到报考信息的你一定会了解到，这所学校与一带一路密不可分",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "Api Overview",
    "path": "api/api-overview",
    "category": "api",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-03T12:44:22+08:00"
  },
  {
    "type": "page",
    "title": "Endpoints",
    "path": "api/endpoints",
    "category": "api",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-03T12:44:22+08:00"
  }
];

export const home = {
  "type": "page",
  "title": "欢迎来到 XMUM Wiki",
  "path": "README",
  "category": "",
  "icon": "",
  "order": null,
  "description": "欢迎来到厦门大学马来西亚分校自救指南/XMUM Wiki！本项目旨在为厦大马校的同学们提供一个全面的信息共享平台，帮助大家更好地适应和享受在马校的学习与生活。",
  "tags": [],
  "headings": [],
  "draft": false,
  "lastUpdated": "2025-06-21T18:29:01+08:00"
};

export const generatedAt = "2026-06-13T15:55:02.440Z";
