// ⚠️ AUTO-GENERATED by scripts/generate-manifest.mjs — do not edit by hand.
// Add markdown files under public/docs/ instead; this regenerates on dev/build.
// Generated: 2026-06-13T16:25:28.717Z

export const tree = [
  {
    "type": "page",
    "title": "贡献指南",
    "path": "贡献指南",
    "category": "",
    "icon": "✍️",
    "order": 0,
    "description": "三步即可新增或修改一篇 wiki 文档，零前端知识。",
    "tags": [
      "贡献",
      "帮助",
      "新手"
    ],
    "headings": [
      "三步新增一篇文档",
      "可选：用 Frontmatter 精细控制",
      "可选：为分类命名 / 排序",
      "图片怎么放",
      "背后发生了什么（了解即可）"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T23:57:14+08:00"
  },
  {
    "type": "category",
    "slug": "人生篇",
    "label": "人生篇",
    "icon": "🌏",
    "order": 1,
    "description": "关于厦马的一切——从报考前的疑惑到在校期间的思考与成长。",
    "children": [
      {
        "type": "page",
        "title": "信息素养",
        "path": "人生篇/信息素养",
        "category": "人生篇",
        "icon": "📡",
        "order": 4,
        "description": "在海外如何高效获取和辨别信息",
        "tags": [
          "工具",
          "技能"
        ],
        "headings": [
          "为什么信息素养很重要",
          "科学上网"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.636Z"
      },
      {
        "type": "page",
        "title": "高考招生咨询",
        "path": "人生篇/高考招生咨询",
        "category": "人生篇",
        "icon": "",
        "order": null,
        "description": "请关注厦大马校招办微信公众号获取与高考录取最新信息，本界面内容仅供参考",
        "tags": [],
        "headings": [
          "湖北省"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      },
      {
        "type": "page",
        "title": "关于厦马",
        "path": "人生篇/关于厦马",
        "category": "人生篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [
          "厦马总体介绍",
          "厦马的优势",
          "厦马的劣势",
          "- 985毕业证？留学跳板？你想在厦马有何收获?"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "国际视野",
        "path": "人生篇/国际视野",
        "category": "人生篇",
        "icon": "",
        "order": null,
        "description": "看到报考信息的你一定会了解到，这所学校与一带一路密不可分",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      }
    ]
  },
  {
    "type": "category",
    "slug": "入学篇",
    "label": "入学篇",
    "icon": "✈️",
    "order": 2,
    "description": "从准备出发到顺利入学——签证、行李、机场、迎新的完整攻略。",
    "children": [
      {
        "type": "page",
        "title": "中国新生迎新系统",
        "path": "入学篇/中国新生迎新系统",
        "category": "入学篇",
        "icon": "🖥️",
        "order": 4,
        "description": "新生报到前的系统操作指引",
        "tags": [
          "新生",
          "系统"
        ],
        "headings": [
          "什么是新生迎新系统"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.636Z"
      },
      {
        "type": "page",
        "title": "学校网站和账号管理",
        "path": "入学篇/学校网站和账号管理",
        "category": "入学篇",
        "icon": "🔑",
        "order": 5,
        "description": "学校各类系统的网址、账号注册和密码管理",
        "tags": [
          "系统",
          "必读"
        ],
        "headings": [
          "常用学校系统",
          "初次密码设置"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.636Z"
      },
      {
        "type": "page",
        "title": "防诈骗指南",
        "path": "入学篇/防诈骗指南",
        "category": "入学篇",
        "icon": "🛡️",
        "order": 6,
        "description": "留学生常见骗局识别与防范",
        "tags": [
          "安全",
          "必读"
        ],
        "headings": [
          "代购骗局（ABC骗局）",
          "其他常见骗局",
          "遇到诈骗怎么办"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.637Z"
      },
      {
        "type": "page",
        "title": "吉隆坡机场指南",
        "path": "入学篇/吉隆坡机场指南",
        "category": "入学篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "行前指南",
        "path": "入学篇/行前指南",
        "category": "入学篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [
          "签证（个人签证与随行人员签证）",
          "英语（雅思/托福/PTE)",
          "必备物品"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "LY宿舍",
        "path": "入学篇/宿舍与室友",
        "category": "入学篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [
          "床"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      }
    ]
  },
  {
    "type": "category",
    "slug": "生活篇",
    "label": "生活篇",
    "icon": "🏠",
    "order": 3,
    "description": "校园设施、周边环境、宿舍、交通、银行、医疗——把日子过舒服。",
    "children": [
      {
        "type": "page",
        "title": "学校设施",
        "path": "生活篇/学校设施",
        "category": "生活篇",
        "icon": "🏫",
        "order": 5,
        "description": "厦马校园设施详解——图书馆、教学楼、宿舍、健身房",
        "tags": [
          "校园",
          "设施"
        ],
        "headings": [
          "图书馆（A3）",
          "打印机的使用方式",
          "教学楼",
          "A1",
          "A2",
          "A4",
          "A5",
          "B1",
          "健身房",
          "超市",
          "活动区域",
          "D区宿舍",
          "D1 / D2 / D3 / D4 / D5",
          "LY区宿舍",
          "LY1 / LY2 / LY4 / LY5 / LY6 / LY7 / LY8 / LY9",
          "LY3 食堂",
          "D6 食堂",
          "酒店"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "学校周边",
        "path": "生活篇/学校周边",
        "category": "生活篇",
        "icon": "🍜",
        "order": 6,
        "description": "厦马周边餐厅、商场、便利店、诊所全攻略",
        "tags": [
          "生活",
          "美食",
          "周边"
        ],
        "headings": [
          "餐厅推荐",
          "Bell（学校对面商业区）",
          "壹碗湘",
          "马壮壮螺蛳粉",
          "EATHAMI（轻食）",
          "钵钵鸡",
          "三千尺",
          "鸡公煲",
          "面对面",
          "佳粤",
          "秀海福麻辣烫",
          "百家牛肉面",
          "麻辣诱惑（麻辣烫）",
          "蜀都风味（火锅）",
          "盛庄水果店",
          "华莱士",
          "南洋餐馆",
          "大圣烧烤",
          "超市",
          "薯嘟嘟 Dudupotato（中国超市）",
          "闽桂 MingGui（中国超市）",
          "便利店",
          "711",
          "KK（便利店）",
          "医疗",
          "Horizon 诊所",
          "购物中心",
          "IOI City Mall（Putrajaya）",
          "如何与行政部门打交道"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "如何与行政部门打交道",
        "path": "生活篇/如何与行政部门打交道",
        "category": "生活篇",
        "icon": "🏛️",
        "order": 7,
        "description": "学校各行政部门的职能、联系方式与办事技巧",
        "tags": [
          "校园",
          "行政"
        ],
        "headings": [
          "总体建议",
          "104 — 学生事务处（Student Affairs Office）",
          "107",
          "109"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "开房（酒店与短租）",
        "path": "生活篇/开房",
        "category": "生活篇",
        "icon": "🏨",
        "order": 8,
        "description": "校外短期住宿、酒店预订攻略",
        "tags": [
          "生活",
          "住宿"
        ],
        "headings": [
          "为什么需要开房"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.637Z"
      },
      {
        "type": "page",
        "title": "校外公寓与租房",
        "path": "生活篇/校外公寓与租房",
        "category": "生活篇",
        "icon": "🏘️",
        "order": 9,
        "description": "校外公寓选择、租房流程与注意事项",
        "tags": [
          "生活",
          "住宿",
          "租房"
        ],
        "headings": [
          "为什么选择校外住宿",
          "租房攻略",
          "合同与押金"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.637Z"
      },
      {
        "type": "page",
        "title": "本地银行卡办理",
        "path": "生活篇/本地银行卡办理",
        "category": "生活篇",
        "icon": "💳",
        "order": 10,
        "description": "马来西亚银行卡办理流程，以 Maybank 为例",
        "tags": [
          "生活",
          "银行",
          "财务"
        ],
        "headings": [
          "为什么需要本地银行卡",
          "Maybank（马来亚银行）办卡流程",
          "其他银行选择"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.637Z"
      },
      {
        "type": "page",
        "title": "带宠物回国",
        "path": "生活篇/带宠物回国",
        "category": "生活篇",
        "icon": "🐱",
        "order": 11,
        "description": "从马来西亚带猫狗等宠物回中国的完整攻略（DIY版）",
        "tags": [
          "生活",
          "宠物"
        ],
        "headings": [
          "基本流程概览",
          "猫咪篇"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.637Z"
      },
      {
        "type": "page",
        "title": "二次元指南",
        "path": "生活篇/二次元指南",
        "category": "生活篇",
        "icon": "🎌",
        "order": 12,
        "description": "厦马二次元同学的兴趣交流与活动指南",
        "tags": [
          "生活",
          "兴趣"
        ],
        "headings": [
          "厦马二次元社团与活动"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.637Z"
      },
      {
        "type": "page",
        "title": "好物分享",
        "path": "生活篇/好物分享",
        "category": "生活篇",
        "icon": "🛒",
        "order": 13,
        "description": "在马来西亚生活必备好物推荐",
        "tags": [
          "生活",
          "购物"
        ],
        "headings": [
          "电子设备",
          "日用品",
          "食品",
          "App推荐"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "马来西亚日常生活",
        "path": "生活篇/马来西亚日常生活",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "Grab(打车＋外卖）",
        "tags": [],
        "headings": [
          "外卖软件"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      },
      {
        "type": "page",
        "title": "医疗",
        "path": "生活篇/医疗",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "智齿，智慧齿(wisdom teeth)常生长于18-19岁及以上的命苦大学生。智齿长出来时易挤压周边牙齿导致牙周炎和盲袋发炎，每个人智齿的生长情况各异，但拔掉智齿对大多数人来说是…",
        "tags": [],
        "headings": [
          "拔智齿"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T18:29:01+08:00"
      },
      {
        "type": "page",
        "title": "运动",
        "path": "生活篇/运动",
        "category": "生活篇",
        "icon": "",
        "order": null,
        "description": "生命在于运动。",
        "tags": [],
        "headings": [
          "校内运动场地",
          "各项运动氛围",
          "校运会Xenergy",
          "校外运动场地推荐"
        ],
        "draft": false,
        "lastUpdated": "2025-06-21T16:03:15+08:00"
      }
    ]
  },
  {
    "type": "category",
    "slug": "学习篇",
    "label": "学习篇",
    "icon": "🎓",
    "order": 4,
    "description": "自学、工具、GPA、选课、小组作业、毕业论文，帮你搞定厦马学业。",
    "children": [
      {
        "type": "page",
        "title": "盲打与提高打字速度",
        "path": "学习篇/盲打与打字速度",
        "category": "学习篇",
        "icon": "⌨️",
        "order": 1,
        "description": "为什么盲打重要，以及如何科学练习",
        "tags": [
          "技能",
          "效率"
        ],
        "headings": [
          "为什么要学盲打",
          "练习工具",
          "进阶：提高英文打字速度"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "全专业通用学习网站",
        "path": "学习篇/全专业通用网站",
        "category": "学习篇",
        "icon": "🌐",
        "order": 5,
        "description": "不限专业通用的学习资源网站汇总",
        "tags": [
          "学习",
          "工具",
          "资源"
        ],
        "headings": [
          "学术资源",
          "设计与制作",
          "写作辅助",
          "笔记与知识管理"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "善用工具",
        "path": "学习篇/善用工具",
        "category": "学习篇",
        "icon": "🛠️",
        "order": 6,
        "description": "Word进阶、DeepL、Grammarly、LaTeX、AI工具使用指南",
        "tags": [
          "学习",
          "工具",
          "效率"
        ],
        "headings": [
          "Word 进阶功能",
          "自动目录（Table of Contents）",
          "Reference / 参考文献",
          "DeepL",
          "Grammarly",
          "Notion",
          "LaTeX",
          "知云文献翻译器",
          "AI 工具（ChatGPT / Claude / Gemini / DeepSeek...）",
          "Midjourney（AI绘图）"
        ],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "GPA计算与管理",
        "path": "学习篇/GPA计算与管理",
        "category": "学习篇",
        "icon": "📊",
        "order": 7,
        "description": "厦马GPA计算规则、GE课程与选课策略",
        "tags": [
          "学习",
          "GPA",
          "选课"
        ],
        "headings": [
          "GPA的计算",
          "GE课程（General Education）",
          "选课技巧",
          "GE 红榜（推荐课程/老师）",
          "GE 黑榜（需谨慎）"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "转专业指南",
        "path": "学习篇/转专业指南",
        "category": "学习篇",
        "icon": "🔄",
        "order": 8,
        "description": "厦马转专业流程、条件与注意事项",
        "tags": [
          "学习",
          "转专业"
        ],
        "headings": [
          "为什么转专业",
          "同大类转专业",
          "跨大类转专业",
          "特殊要求专业：会计/金融",
          "转过专业的学长学姐心声"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "AC系统使用指南",
        "path": "学习篇/AC系统使用指南",
        "category": "学习篇",
        "icon": "🖥️",
        "order": 9,
        "description": "学校AC（Academic Calendar）系统操作指引",
        "tags": [
          "学习",
          "系统"
        ],
        "headings": [
          "什么是AC系统"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "寻找科研和项目经验",
        "path": "学习篇/科研与项目经验",
        "category": "学习篇",
        "icon": "🔬",
        "order": 10,
        "description": "如何在厦马找到科研机会、参与项目",
        "tags": [
          "学习",
          "科研",
          "经历"
        ],
        "headings": [
          "为什么科研经验很重要",
          "如何寻找科研机会",
          "推荐邮件模板"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "突击备考",
        "path": "学习篇/突击备考",
        "category": "学习篇",
        "icon": "📚",
        "order": 11,
        "description": "考前高效备考策略与资源整理",
        "tags": [
          "学习",
          "考试"
        ],
        "headings": [
          "考前一周计划",
          "历年真题与资源",
          "不同类型科目的备考策略",
          "记忆型科目（Marketing、Management 等）",
          "计算型科目（Math、Accounting 等）",
          "编程类科目"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "毕业论文与毕业设计",
        "path": "学习篇/毕业论文与毕业设计",
        "category": "学习篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "小组作业生存指南",
        "path": "学习篇/小组作业生存指南",
        "category": "学习篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      },
      {
        "type": "page",
        "title": "自学",
        "path": "学习篇/自学",
        "category": "学习篇",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-11T00:52:19+08:00"
      }
    ]
  },
  {
    "type": "category",
    "slug": "专业篇",
    "label": "专业篇",
    "icon": "🎯",
    "order": 5,
    "description": "厦马各专业介绍、课程设置、就业方向与学长学姐经验分享。",
    "children": [
      {
        "type": "page",
        "title": "ECM电子商务",
        "path": "专业篇/ECM电子商务",
        "category": "专业篇",
        "icon": "🛒",
        "order": 1,
        "description": "ECM电子商务（Electronic Commerce）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "ECM电子商务"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "CHS汉语言文学",
        "path": "专业篇/CHS汉语言文学",
        "category": "专业篇",
        "icon": "📖",
        "order": 2,
        "description": "CHS汉语言文学（Chinese Language & Literature）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "CHS汉语言文学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "ACC会计学",
        "path": "专业篇/ACC会计学",
        "category": "专业篇",
        "icon": "💰",
        "order": 3,
        "description": "ACC会计学（Accounting）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "ACC会计学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "IBU国际商务",
        "path": "专业篇/IBU国际商务",
        "category": "专业篇",
        "icon": "🌐",
        "order": 4,
        "description": "IBU国际商务（International Business）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "IBU国际商务"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "FIN金融学",
        "path": "专业篇/FIN金融学",
        "category": "专业篇",
        "icon": "📈",
        "order": 5,
        "description": "FIN金融学（Finance）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "FIN金融学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.638Z"
      },
      {
        "type": "page",
        "title": "ENG英语",
        "path": "专业篇/ENG英语",
        "category": "专业篇",
        "icon": "🔤",
        "order": 6,
        "description": "ENG英语（English Language & Literature）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "ENG英语"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "ADT广告学",
        "path": "专业篇/ADT广告学",
        "category": "专业篇",
        "icon": "📢",
        "order": 7,
        "description": "ADT广告学（Advertising）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "ADT广告学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "JRN新闻学",
        "path": "专业篇/JRN新闻学",
        "category": "专业篇",
        "icon": "📰",
        "order": 8,
        "description": "JRN新闻学（Journalism）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "JRN新闻学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "COS传播学",
        "path": "专业篇/COS传播学",
        "category": "专业篇",
        "icon": "📡",
        "order": 9,
        "description": "COS传播学（Communication Studies）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "COS传播学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "CYS网络空间安全",
        "path": "专业篇/CYS网络空间安全",
        "category": "专业篇",
        "icon": "🔐",
        "order": 10,
        "description": "CYS网络空间安全（Cyber Security）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "CYS网络空间安全"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "MAT数学与应用数学",
        "path": "专业篇/MAT数学与应用数学",
        "category": "专业篇",
        "icon": "📐",
        "order": 11,
        "description": "MAT数学与应用数学（Mathematics）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "MAT数学与应用数学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "PHY物理学",
        "path": "专业篇/PHY物理学",
        "category": "专业篇",
        "icon": "⚛️",
        "order": 12,
        "description": "PHY物理学（Physics）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "PHY物理学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "CST计算机科学与技术",
        "path": "专业篇/CST计算机科学与技术",
        "category": "专业篇",
        "icon": "💻",
        "order": 13,
        "description": "CST计算机科学与技术（Computer Science & Technology）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "CST计算机科学与技术"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "AIT人工智能",
        "path": "专业篇/AIT人工智能",
        "category": "专业篇",
        "icon": "🤖",
        "order": 14,
        "description": "AIT人工智能（Artificial Intelligence）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "AIT人工智能"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "SWE软件工程",
        "path": "专业篇/SWE软件工程",
        "category": "专业篇",
        "icon": "🛠️",
        "order": 15,
        "description": "SWE软件工程（Software Engineering）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "SWE软件工程"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "MBT海洋技术",
        "path": "专业篇/MBT海洋技术",
        "category": "专业篇",
        "icon": "🌊",
        "order": 16,
        "description": "MBT海洋技术（Marine Technology）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "MBT海洋技术"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "MEC海洋科学",
        "path": "专业篇/MEC海洋科学",
        "category": "专业篇",
        "icon": "🐋",
        "order": 17,
        "description": "MEC海洋科学（Marine Science）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "MEC海洋科学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "TCM中医学",
        "path": "专业篇/TCM中医学",
        "category": "专业篇",
        "icon": "🌿",
        "order": 18,
        "description": "TCM中医学（Traditional Chinese Medicine）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "TCM中医学"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "CME化学工程与工艺",
        "path": "专业篇/CME化学工程与工艺",
        "category": "专业篇",
        "icon": "⚗️",
        "order": 19,
        "description": "CME化学工程与工艺（Chemical Engineering）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "CME化学工程与工艺"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "EEE电子信息技术",
        "path": "专业篇/EEE电子信息技术",
        "category": "专业篇",
        "icon": "📟",
        "order": 20,
        "description": "EEE电子信息技术（Electrical & Electronic Engineering）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "EEE电子信息技术"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "DMT数字媒体技术",
        "path": "专业篇/DMT数字媒体技术",
        "category": "专业篇",
        "icon": "🎬",
        "order": 21,
        "description": "DMT数字媒体技术（Digital Media Technology）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "DMT数字媒体技术"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.639Z"
      },
      {
        "type": "page",
        "title": "FIA文科预科班",
        "path": "专业篇/FIA文科预科班",
        "category": "专业篇",
        "icon": "📝",
        "order": 22,
        "description": "FIA文科预科班（Foundation in Arts）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "FIA文科预科班"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.640Z"
      },
      {
        "type": "page",
        "title": "FIS理科预科班",
        "path": "专业篇/FIS理科预科班",
        "category": "专业篇",
        "icon": "🔬",
        "order": 23,
        "description": "FIS理科预科班（Foundation in Science）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "FIS理科预科班"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.640Z"
      },
      {
        "type": "page",
        "title": "EGE新能源",
        "path": "专业篇/EGE新能源",
        "category": "专业篇",
        "icon": "🌱",
        "order": 24,
        "description": "EGE新能源（Energy Engineering）专业介绍、课程与经验分享",
        "tags": [
          "专业",
          "EGE新能源"
        ],
        "headings": [
          "专业简介",
          "主要课程",
          "就业方向",
          "考研/申研方向",
          "学长学姐经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.640Z"
      }
    ]
  },
  {
    "type": "category",
    "slug": "升学篇",
    "label": "升学篇",
    "icon": "🎓",
    "order": 6,
    "description": "申研、保研、考研——从厦马出发的升学路线全解析。",
    "children": [
      {
        "type": "page",
        "title": "申研（留学申请）",
        "path": "升学篇/申研",
        "category": "升学篇",
        "icon": "✈️",
        "order": 1,
        "description": "留学申请全流程——选校、材料准备、语言考试、中介避坑",
        "tags": [
          "升学",
          "申研",
          "留学"
        ],
        "headings": [
          "为什么继续留学",
          "国家/地区的选择",
          "读什么学位/专业",
          "润学",
          "在厦马期间需要准备什么",
          "外语考试",
          "科研经历",
          "竞赛经历",
          "推荐信",
          "实习经历",
          "警惕中介",
          "国际局势下的留学新常态"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.640Z"
      },
      {
        "type": "page",
        "title": "保研（推免）",
        "path": "升学篇/保研",
        "category": "升学篇",
        "icon": "🏅",
        "order": 2,
        "description": "厦马学生回国保研的路径、条件与经验分享",
        "tags": [
          "升学",
          "保研",
          "国内"
        ],
        "headings": [
          "厦马学生能否保研",
          "GPA 和排名",
          "竞赛",
          "计算机大类专业视角",
          "科研",
          "夏令营"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.640Z"
      },
      {
        "type": "page",
        "title": "考研",
        "path": "升学篇/考研",
        "category": "升学篇",
        "icon": "📝",
        "order": 3,
        "description": "厦马学生参加中国大陆研究生考试的指南",
        "tags": [
          "升学",
          "考研",
          "国内"
        ],
        "headings": [
          "厦马学生能否参加考研",
          "择校经验",
          "备考资源",
          "面对问题"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.640Z"
      }
    ]
  },
  {
    "type": "category",
    "slug": "走进社会篇",
    "label": "走进社会篇",
    "icon": "💼",
    "order": 7,
    "description": "实习、求职、面试——从校园走向职场的经验总结。",
    "children": [
      {
        "type": "page",
        "title": "经典面试问题与回答技巧",
        "path": "走进社会篇/经典面试问题",
        "category": "走进社会篇",
        "icon": "🎤",
        "order": 1,
        "description": "常见面试问题汇总与回答思路",
        "tags": [
          "求职",
          "面试"
        ],
        "headings": [
          "自我介绍",
          "常见问题",
          "\"你最大的优点/缺点是什么？\"",
          "\"你为什么选择我们公司？\"",
          "\"你有什么职业规划？\"",
          "\"你期望的薪资是多少？\"",
          "压力面试与群面",
          "英文面试技巧"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.641Z"
      },
      {
        "type": "page",
        "title": "实习指南",
        "path": "走进社会篇/实习",
        "category": "走进社会篇",
        "icon": "🏢",
        "order": 2,
        "description": "实习要求、寻找渠道、避坑与经验分享",
        "tags": [
          "求职",
          "实习"
        ],
        "headings": [
          "我校实习要求时间",
          "寻找实习的准备",
          "实习避坑指南",
          "实习经验分享"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.641Z"
      },
      {
        "type": "page",
        "title": "工作感想",
        "path": "走进社会篇/工作感想",
        "category": "走进社会篇",
        "icon": "💡",
        "order": 3,
        "description": "厦马毕业生在各类岗位的真实工作感想",
        "tags": [
          "求职",
          "工作"
        ],
        "headings": [
          "总体感想",
          "国企",
          "私企",
          "外企",
          "体制内（公务员/事业单位）",
          "教师",
          "自由职业",
          "无业（Gap Year / 慢就业）"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.641Z"
      }
    ]
  },
  {
    "type": "category",
    "slug": "访谈篇",
    "label": "访谈篇",
    "icon": "🎙️",
    "order": 8,
    "description": "厦马学长学姐的亲身经历与心里话——最真实的参考。",
    "children": [
      {
        "type": "page",
        "title": "访谈篇简介",
        "path": "访谈篇/README",
        "category": "访谈篇",
        "icon": "🎙️",
        "order": 0,
        "description": "厦马各届学长学姐的访谈与心声合集",
        "tags": [
          "访谈",
          "经验"
        ],
        "headings": [
          "关于访谈篇",
          "如何参与",
          "你还有什么想对同学们说的？"
        ],
        "draft": false,
        "lastUpdated": "2026-06-13T16:25:07.641Z"
      }
    ]
  },
  {
    "type": "category",
    "slug": "api",
    "label": "开发文档",
    "icon": "🔌",
    "order": 9,
    "description": "面向开发者：站点 API 概览与接口列表。",
    "children": [
      {
        "type": "page",
        "title": "Api Overview",
        "path": "api/api-overview",
        "category": "api",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-03T12:44:22+08:00"
      },
      {
        "type": "page",
        "title": "Endpoints",
        "path": "api/endpoints",
        "category": "api",
        "icon": "",
        "order": null,
        "description": "",
        "tags": [],
        "headings": [],
        "draft": false,
        "lastUpdated": "2025-06-03T12:44:22+08:00"
      }
    ]
  }
];

export const pages = [
  {
    "type": "page",
    "title": "欢迎来到 XMUM Wiki",
    "path": "README",
    "category": "",
    "icon": "",
    "order": null,
    "description": "欢迎来到厦门大学马来西亚分校自救指南/XMUM Wiki！本项目旨在为厦大马校的同学们提供一个全面的信息共享平台，帮助大家更好地适应和享受在马校的学习与生活。",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-21T18:29:01+08:00"
  },
  {
    "type": "page",
    "title": "贡献指南",
    "path": "贡献指南",
    "category": "",
    "icon": "✍️",
    "order": 0,
    "description": "三步即可新增或修改一篇 wiki 文档，零前端知识。",
    "tags": [
      "贡献",
      "帮助",
      "新手"
    ],
    "headings": [
      "三步新增一篇文档",
      "可选：用 Frontmatter 精细控制",
      "可选：为分类命名 / 排序",
      "图片怎么放",
      "背后发生了什么（了解即可）"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T23:57:14+08:00"
  },
  {
    "type": "page",
    "title": "信息素养",
    "path": "人生篇/信息素养",
    "category": "人生篇",
    "icon": "📡",
    "order": 4,
    "description": "在海外如何高效获取和辨别信息",
    "tags": [
      "工具",
      "技能"
    ],
    "headings": [
      "为什么信息素养很重要",
      "科学上网"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.636Z"
  },
  {
    "type": "page",
    "title": "高考招生咨询",
    "path": "人生篇/高考招生咨询",
    "category": "人生篇",
    "icon": "",
    "order": null,
    "description": "请关注厦大马校招办微信公众号获取与高考录取最新信息，本界面内容仅供参考",
    "tags": [],
    "headings": [
      "湖北省"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "关于厦马",
    "path": "人生篇/关于厦马",
    "category": "人生篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [
      "厦马总体介绍",
      "厦马的优势",
      "厦马的劣势",
      "- 985毕业证？留学跳板？你想在厦马有何收获?"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "国际视野",
    "path": "人生篇/国际视野",
    "category": "人生篇",
    "icon": "",
    "order": null,
    "description": "看到报考信息的你一定会了解到，这所学校与一带一路密不可分",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "中国新生迎新系统",
    "path": "入学篇/中国新生迎新系统",
    "category": "入学篇",
    "icon": "🖥️",
    "order": 4,
    "description": "新生报到前的系统操作指引",
    "tags": [
      "新生",
      "系统"
    ],
    "headings": [
      "什么是新生迎新系统"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.636Z"
  },
  {
    "type": "page",
    "title": "学校网站和账号管理",
    "path": "入学篇/学校网站和账号管理",
    "category": "入学篇",
    "icon": "🔑",
    "order": 5,
    "description": "学校各类系统的网址、账号注册和密码管理",
    "tags": [
      "系统",
      "必读"
    ],
    "headings": [
      "常用学校系统",
      "初次密码设置"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.636Z"
  },
  {
    "type": "page",
    "title": "防诈骗指南",
    "path": "入学篇/防诈骗指南",
    "category": "入学篇",
    "icon": "🛡️",
    "order": 6,
    "description": "留学生常见骗局识别与防范",
    "tags": [
      "安全",
      "必读"
    ],
    "headings": [
      "代购骗局（ABC骗局）",
      "其他常见骗局",
      "遇到诈骗怎么办"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.637Z"
  },
  {
    "type": "page",
    "title": "吉隆坡机场指南",
    "path": "入学篇/吉隆坡机场指南",
    "category": "入学篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "行前指南",
    "path": "入学篇/行前指南",
    "category": "入学篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [
      "签证（个人签证与随行人员签证）",
      "英语（雅思/托福/PTE)",
      "必备物品"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "LY宿舍",
    "path": "入学篇/宿舍与室友",
    "category": "入学篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [
      "床"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "学校设施",
    "path": "生活篇/学校设施",
    "category": "生活篇",
    "icon": "🏫",
    "order": 5,
    "description": "厦马校园设施详解——图书馆、教学楼、宿舍、健身房",
    "tags": [
      "校园",
      "设施"
    ],
    "headings": [
      "图书馆（A3）",
      "打印机的使用方式",
      "教学楼",
      "A1",
      "A2",
      "A4",
      "A5",
      "B1",
      "健身房",
      "超市",
      "活动区域",
      "D区宿舍",
      "D1 / D2 / D3 / D4 / D5",
      "LY区宿舍",
      "LY1 / LY2 / LY4 / LY5 / LY6 / LY7 / LY8 / LY9",
      "LY3 食堂",
      "D6 食堂",
      "酒店"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "学校周边",
    "path": "生活篇/学校周边",
    "category": "生活篇",
    "icon": "🍜",
    "order": 6,
    "description": "厦马周边餐厅、商场、便利店、诊所全攻略",
    "tags": [
      "生活",
      "美食",
      "周边"
    ],
    "headings": [
      "餐厅推荐",
      "Bell（学校对面商业区）",
      "壹碗湘",
      "马壮壮螺蛳粉",
      "EATHAMI（轻食）",
      "钵钵鸡",
      "三千尺",
      "鸡公煲",
      "面对面",
      "佳粤",
      "秀海福麻辣烫",
      "百家牛肉面",
      "麻辣诱惑（麻辣烫）",
      "蜀都风味（火锅）",
      "盛庄水果店",
      "华莱士",
      "南洋餐馆",
      "大圣烧烤",
      "超市",
      "薯嘟嘟 Dudupotato（中国超市）",
      "闽桂 MingGui（中国超市）",
      "便利店",
      "711",
      "KK（便利店）",
      "医疗",
      "Horizon 诊所",
      "购物中心",
      "IOI City Mall（Putrajaya）",
      "如何与行政部门打交道"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "如何与行政部门打交道",
    "path": "生活篇/如何与行政部门打交道",
    "category": "生活篇",
    "icon": "🏛️",
    "order": 7,
    "description": "学校各行政部门的职能、联系方式与办事技巧",
    "tags": [
      "校园",
      "行政"
    ],
    "headings": [
      "总体建议",
      "104 — 学生事务处（Student Affairs Office）",
      "107",
      "109"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "开房（酒店与短租）",
    "path": "生活篇/开房",
    "category": "生活篇",
    "icon": "🏨",
    "order": 8,
    "description": "校外短期住宿、酒店预订攻略",
    "tags": [
      "生活",
      "住宿"
    ],
    "headings": [
      "为什么需要开房"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.637Z"
  },
  {
    "type": "page",
    "title": "校外公寓与租房",
    "path": "生活篇/校外公寓与租房",
    "category": "生活篇",
    "icon": "🏘️",
    "order": 9,
    "description": "校外公寓选择、租房流程与注意事项",
    "tags": [
      "生活",
      "住宿",
      "租房"
    ],
    "headings": [
      "为什么选择校外住宿",
      "租房攻略",
      "合同与押金"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.637Z"
  },
  {
    "type": "page",
    "title": "本地银行卡办理",
    "path": "生活篇/本地银行卡办理",
    "category": "生活篇",
    "icon": "💳",
    "order": 10,
    "description": "马来西亚银行卡办理流程，以 Maybank 为例",
    "tags": [
      "生活",
      "银行",
      "财务"
    ],
    "headings": [
      "为什么需要本地银行卡",
      "Maybank（马来亚银行）办卡流程",
      "其他银行选择"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.637Z"
  },
  {
    "type": "page",
    "title": "带宠物回国",
    "path": "生活篇/带宠物回国",
    "category": "生活篇",
    "icon": "🐱",
    "order": 11,
    "description": "从马来西亚带猫狗等宠物回中国的完整攻略（DIY版）",
    "tags": [
      "生活",
      "宠物"
    ],
    "headings": [
      "基本流程概览",
      "猫咪篇"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.637Z"
  },
  {
    "type": "page",
    "title": "二次元指南",
    "path": "生活篇/二次元指南",
    "category": "生活篇",
    "icon": "🎌",
    "order": 12,
    "description": "厦马二次元同学的兴趣交流与活动指南",
    "tags": [
      "生活",
      "兴趣"
    ],
    "headings": [
      "厦马二次元社团与活动"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.637Z"
  },
  {
    "type": "page",
    "title": "好物分享",
    "path": "生活篇/好物分享",
    "category": "生活篇",
    "icon": "🛒",
    "order": 13,
    "description": "在马来西亚生活必备好物推荐",
    "tags": [
      "生活",
      "购物"
    ],
    "headings": [
      "电子设备",
      "日用品",
      "食品",
      "App推荐"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "马来西亚日常生活",
    "path": "生活篇/马来西亚日常生活",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "Grab(打车＋外卖）",
    "tags": [],
    "headings": [
      "外卖软件"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "医疗",
    "path": "生活篇/医疗",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "智齿，智慧齿(wisdom teeth)常生长于18-19岁及以上的命苦大学生。智齿长出来时易挤压周边牙齿导致牙周炎和盲袋发炎，每个人智齿的生长情况各异，但拔掉智齿对大多数人来说是…",
    "tags": [],
    "headings": [
      "拔智齿"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T18:29:01+08:00"
  },
  {
    "type": "page",
    "title": "运动",
    "path": "生活篇/运动",
    "category": "生活篇",
    "icon": "",
    "order": null,
    "description": "生命在于运动。",
    "tags": [],
    "headings": [
      "校内运动场地",
      "各项运动氛围",
      "校运会Xenergy",
      "校外运动场地推荐"
    ],
    "draft": false,
    "lastUpdated": "2025-06-21T16:03:15+08:00"
  },
  {
    "type": "page",
    "title": "盲打与提高打字速度",
    "path": "学习篇/盲打与打字速度",
    "category": "学习篇",
    "icon": "⌨️",
    "order": 1,
    "description": "为什么盲打重要，以及如何科学练习",
    "tags": [
      "技能",
      "效率"
    ],
    "headings": [
      "为什么要学盲打",
      "练习工具",
      "进阶：提高英文打字速度"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "全专业通用学习网站",
    "path": "学习篇/全专业通用网站",
    "category": "学习篇",
    "icon": "🌐",
    "order": 5,
    "description": "不限专业通用的学习资源网站汇总",
    "tags": [
      "学习",
      "工具",
      "资源"
    ],
    "headings": [
      "学术资源",
      "设计与制作",
      "写作辅助",
      "笔记与知识管理"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "善用工具",
    "path": "学习篇/善用工具",
    "category": "学习篇",
    "icon": "🛠️",
    "order": 6,
    "description": "Word进阶、DeepL、Grammarly、LaTeX、AI工具使用指南",
    "tags": [
      "学习",
      "工具",
      "效率"
    ],
    "headings": [
      "Word 进阶功能",
      "自动目录（Table of Contents）",
      "Reference / 参考文献",
      "DeepL",
      "Grammarly",
      "Notion",
      "LaTeX",
      "知云文献翻译器",
      "AI 工具（ChatGPT / Claude / Gemini / DeepSeek...）",
      "Midjourney（AI绘图）"
    ],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "GPA计算与管理",
    "path": "学习篇/GPA计算与管理",
    "category": "学习篇",
    "icon": "📊",
    "order": 7,
    "description": "厦马GPA计算规则、GE课程与选课策略",
    "tags": [
      "学习",
      "GPA",
      "选课"
    ],
    "headings": [
      "GPA的计算",
      "GE课程（General Education）",
      "选课技巧",
      "GE 红榜（推荐课程/老师）",
      "GE 黑榜（需谨慎）"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "转专业指南",
    "path": "学习篇/转专业指南",
    "category": "学习篇",
    "icon": "🔄",
    "order": 8,
    "description": "厦马转专业流程、条件与注意事项",
    "tags": [
      "学习",
      "转专业"
    ],
    "headings": [
      "为什么转专业",
      "同大类转专业",
      "跨大类转专业",
      "特殊要求专业：会计/金融",
      "转过专业的学长学姐心声"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "AC系统使用指南",
    "path": "学习篇/AC系统使用指南",
    "category": "学习篇",
    "icon": "🖥️",
    "order": 9,
    "description": "学校AC（Academic Calendar）系统操作指引",
    "tags": [
      "学习",
      "系统"
    ],
    "headings": [
      "什么是AC系统"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "寻找科研和项目经验",
    "path": "学习篇/科研与项目经验",
    "category": "学习篇",
    "icon": "🔬",
    "order": 10,
    "description": "如何在厦马找到科研机会、参与项目",
    "tags": [
      "学习",
      "科研",
      "经历"
    ],
    "headings": [
      "为什么科研经验很重要",
      "如何寻找科研机会",
      "推荐邮件模板"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "突击备考",
    "path": "学习篇/突击备考",
    "category": "学习篇",
    "icon": "📚",
    "order": 11,
    "description": "考前高效备考策略与资源整理",
    "tags": [
      "学习",
      "考试"
    ],
    "headings": [
      "考前一周计划",
      "历年真题与资源",
      "不同类型科目的备考策略",
      "记忆型科目（Marketing、Management 等）",
      "计算型科目（Math、Accounting 等）",
      "编程类科目"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "毕业论文与毕业设计",
    "path": "学习篇/毕业论文与毕业设计",
    "category": "学习篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "小组作业生存指南",
    "path": "学习篇/小组作业生存指南",
    "category": "学习篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "自学",
    "path": "学习篇/自学",
    "category": "学习篇",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-11T00:52:19+08:00"
  },
  {
    "type": "page",
    "title": "ECM电子商务",
    "path": "专业篇/ECM电子商务",
    "category": "专业篇",
    "icon": "🛒",
    "order": 1,
    "description": "ECM电子商务（Electronic Commerce）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "ECM电子商务"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "CHS汉语言文学",
    "path": "专业篇/CHS汉语言文学",
    "category": "专业篇",
    "icon": "📖",
    "order": 2,
    "description": "CHS汉语言文学（Chinese Language & Literature）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "CHS汉语言文学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "ACC会计学",
    "path": "专业篇/ACC会计学",
    "category": "专业篇",
    "icon": "💰",
    "order": 3,
    "description": "ACC会计学（Accounting）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "ACC会计学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "IBU国际商务",
    "path": "专业篇/IBU国际商务",
    "category": "专业篇",
    "icon": "🌐",
    "order": 4,
    "description": "IBU国际商务（International Business）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "IBU国际商务"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "FIN金融学",
    "path": "专业篇/FIN金融学",
    "category": "专业篇",
    "icon": "📈",
    "order": 5,
    "description": "FIN金融学（Finance）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "FIN金融学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.638Z"
  },
  {
    "type": "page",
    "title": "ENG英语",
    "path": "专业篇/ENG英语",
    "category": "专业篇",
    "icon": "🔤",
    "order": 6,
    "description": "ENG英语（English Language & Literature）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "ENG英语"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "ADT广告学",
    "path": "专业篇/ADT广告学",
    "category": "专业篇",
    "icon": "📢",
    "order": 7,
    "description": "ADT广告学（Advertising）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "ADT广告学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "JRN新闻学",
    "path": "专业篇/JRN新闻学",
    "category": "专业篇",
    "icon": "📰",
    "order": 8,
    "description": "JRN新闻学（Journalism）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "JRN新闻学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "COS传播学",
    "path": "专业篇/COS传播学",
    "category": "专业篇",
    "icon": "📡",
    "order": 9,
    "description": "COS传播学（Communication Studies）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "COS传播学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "CYS网络空间安全",
    "path": "专业篇/CYS网络空间安全",
    "category": "专业篇",
    "icon": "🔐",
    "order": 10,
    "description": "CYS网络空间安全（Cyber Security）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "CYS网络空间安全"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "MAT数学与应用数学",
    "path": "专业篇/MAT数学与应用数学",
    "category": "专业篇",
    "icon": "📐",
    "order": 11,
    "description": "MAT数学与应用数学（Mathematics）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "MAT数学与应用数学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "PHY物理学",
    "path": "专业篇/PHY物理学",
    "category": "专业篇",
    "icon": "⚛️",
    "order": 12,
    "description": "PHY物理学（Physics）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "PHY物理学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "CST计算机科学与技术",
    "path": "专业篇/CST计算机科学与技术",
    "category": "专业篇",
    "icon": "💻",
    "order": 13,
    "description": "CST计算机科学与技术（Computer Science & Technology）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "CST计算机科学与技术"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "AIT人工智能",
    "path": "专业篇/AIT人工智能",
    "category": "专业篇",
    "icon": "🤖",
    "order": 14,
    "description": "AIT人工智能（Artificial Intelligence）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "AIT人工智能"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "SWE软件工程",
    "path": "专业篇/SWE软件工程",
    "category": "专业篇",
    "icon": "🛠️",
    "order": 15,
    "description": "SWE软件工程（Software Engineering）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "SWE软件工程"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "MBT海洋技术",
    "path": "专业篇/MBT海洋技术",
    "category": "专业篇",
    "icon": "🌊",
    "order": 16,
    "description": "MBT海洋技术（Marine Technology）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "MBT海洋技术"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "MEC海洋科学",
    "path": "专业篇/MEC海洋科学",
    "category": "专业篇",
    "icon": "🐋",
    "order": 17,
    "description": "MEC海洋科学（Marine Science）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "MEC海洋科学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "TCM中医学",
    "path": "专业篇/TCM中医学",
    "category": "专业篇",
    "icon": "🌿",
    "order": 18,
    "description": "TCM中医学（Traditional Chinese Medicine）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "TCM中医学"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "CME化学工程与工艺",
    "path": "专业篇/CME化学工程与工艺",
    "category": "专业篇",
    "icon": "⚗️",
    "order": 19,
    "description": "CME化学工程与工艺（Chemical Engineering）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "CME化学工程与工艺"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "EEE电子信息技术",
    "path": "专业篇/EEE电子信息技术",
    "category": "专业篇",
    "icon": "📟",
    "order": 20,
    "description": "EEE电子信息技术（Electrical & Electronic Engineering）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "EEE电子信息技术"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "DMT数字媒体技术",
    "path": "专业篇/DMT数字媒体技术",
    "category": "专业篇",
    "icon": "🎬",
    "order": 21,
    "description": "DMT数字媒体技术（Digital Media Technology）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "DMT数字媒体技术"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.639Z"
  },
  {
    "type": "page",
    "title": "FIA文科预科班",
    "path": "专业篇/FIA文科预科班",
    "category": "专业篇",
    "icon": "📝",
    "order": 22,
    "description": "FIA文科预科班（Foundation in Arts）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "FIA文科预科班"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.640Z"
  },
  {
    "type": "page",
    "title": "FIS理科预科班",
    "path": "专业篇/FIS理科预科班",
    "category": "专业篇",
    "icon": "🔬",
    "order": 23,
    "description": "FIS理科预科班（Foundation in Science）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "FIS理科预科班"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.640Z"
  },
  {
    "type": "page",
    "title": "EGE新能源",
    "path": "专业篇/EGE新能源",
    "category": "专业篇",
    "icon": "🌱",
    "order": 24,
    "description": "EGE新能源（Energy Engineering）专业介绍、课程与经验分享",
    "tags": [
      "专业",
      "EGE新能源"
    ],
    "headings": [
      "专业简介",
      "主要课程",
      "就业方向",
      "考研/申研方向",
      "学长学姐经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.640Z"
  },
  {
    "type": "page",
    "title": "申研（留学申请）",
    "path": "升学篇/申研",
    "category": "升学篇",
    "icon": "✈️",
    "order": 1,
    "description": "留学申请全流程——选校、材料准备、语言考试、中介避坑",
    "tags": [
      "升学",
      "申研",
      "留学"
    ],
    "headings": [
      "为什么继续留学",
      "国家/地区的选择",
      "读什么学位/专业",
      "润学",
      "在厦马期间需要准备什么",
      "外语考试",
      "科研经历",
      "竞赛经历",
      "推荐信",
      "实习经历",
      "警惕中介",
      "国际局势下的留学新常态"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.640Z"
  },
  {
    "type": "page",
    "title": "保研（推免）",
    "path": "升学篇/保研",
    "category": "升学篇",
    "icon": "🏅",
    "order": 2,
    "description": "厦马学生回国保研的路径、条件与经验分享",
    "tags": [
      "升学",
      "保研",
      "国内"
    ],
    "headings": [
      "厦马学生能否保研",
      "GPA 和排名",
      "竞赛",
      "计算机大类专业视角",
      "科研",
      "夏令营"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.640Z"
  },
  {
    "type": "page",
    "title": "考研",
    "path": "升学篇/考研",
    "category": "升学篇",
    "icon": "📝",
    "order": 3,
    "description": "厦马学生参加中国大陆研究生考试的指南",
    "tags": [
      "升学",
      "考研",
      "国内"
    ],
    "headings": [
      "厦马学生能否参加考研",
      "择校经验",
      "备考资源",
      "面对问题"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.640Z"
  },
  {
    "type": "page",
    "title": "经典面试问题与回答技巧",
    "path": "走进社会篇/经典面试问题",
    "category": "走进社会篇",
    "icon": "🎤",
    "order": 1,
    "description": "常见面试问题汇总与回答思路",
    "tags": [
      "求职",
      "面试"
    ],
    "headings": [
      "自我介绍",
      "常见问题",
      "\"你最大的优点/缺点是什么？\"",
      "\"你为什么选择我们公司？\"",
      "\"你有什么职业规划？\"",
      "\"你期望的薪资是多少？\"",
      "压力面试与群面",
      "英文面试技巧"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.641Z"
  },
  {
    "type": "page",
    "title": "实习指南",
    "path": "走进社会篇/实习",
    "category": "走进社会篇",
    "icon": "🏢",
    "order": 2,
    "description": "实习要求、寻找渠道、避坑与经验分享",
    "tags": [
      "求职",
      "实习"
    ],
    "headings": [
      "我校实习要求时间",
      "寻找实习的准备",
      "实习避坑指南",
      "实习经验分享"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.641Z"
  },
  {
    "type": "page",
    "title": "工作感想",
    "path": "走进社会篇/工作感想",
    "category": "走进社会篇",
    "icon": "💡",
    "order": 3,
    "description": "厦马毕业生在各类岗位的真实工作感想",
    "tags": [
      "求职",
      "工作"
    ],
    "headings": [
      "总体感想",
      "国企",
      "私企",
      "外企",
      "体制内（公务员/事业单位）",
      "教师",
      "自由职业",
      "无业（Gap Year / 慢就业）"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.641Z"
  },
  {
    "type": "page",
    "title": "访谈篇简介",
    "path": "访谈篇/README",
    "category": "访谈篇",
    "icon": "🎙️",
    "order": 0,
    "description": "厦马各届学长学姐的访谈与心声合集",
    "tags": [
      "访谈",
      "经验"
    ],
    "headings": [
      "关于访谈篇",
      "如何参与",
      "你还有什么想对同学们说的？"
    ],
    "draft": false,
    "lastUpdated": "2026-06-13T16:25:07.641Z"
  },
  {
    "type": "page",
    "title": "Api Overview",
    "path": "api/api-overview",
    "category": "api",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-03T12:44:22+08:00"
  },
  {
    "type": "page",
    "title": "Endpoints",
    "path": "api/endpoints",
    "category": "api",
    "icon": "",
    "order": null,
    "description": "",
    "tags": [],
    "headings": [],
    "draft": false,
    "lastUpdated": "2025-06-03T12:44:22+08:00"
  }
];

export const home = {
  "type": "page",
  "title": "欢迎来到 XMUM Wiki",
  "path": "README",
  "category": "",
  "icon": "",
  "order": null,
  "description": "欢迎来到厦门大学马来西亚分校自救指南/XMUM Wiki！本项目旨在为厦大马校的同学们提供一个全面的信息共享平台，帮助大家更好地适应和享受在马校的学习与生活。",
  "tags": [],
  "headings": [],
  "draft": false,
  "lastUpdated": "2025-06-21T18:29:01+08:00"
};

export const generatedAt = "2026-06-13T16:25:28.717Z";
